apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: contribpodman-nextfcos-podmanimage-podman
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: contribpodman-nextfcos-podmanimage-podman
    app.kubernetes.io/part-of: podman
  name: contribpodman-nextfcos-podmanimage-podman
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: contribpodman-nextfcos-podmanimage-podman
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: contribpodman-nextfcos-podmanimage-podman
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
